---
name: BlueStream
description: Seamless Daily Driving with Fedora Silverblue at Its Core.

base-image: quay.io/fedora/fedora-silverblue
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
    install:
      - gnome-shell
      - mutter
      - mutter-common
      - xorg-x11-server-Xwayland
      - gdm
    remove:
      - gnome-tour
      - yelp
      - gnome-software-rpm-ostree
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-background-logo

  - type: signing