---
name: BlueStream
description: Seamless Daily Computing with Fedora Silverblue at Its Core.

base-image: quay.io/fedora/fedora-silverblue
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: bling
    install:
        - rpmfusion
        - dconf-update-service

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://copr.fedorainfracloud.org/coprs/wojnilowicz/ungoogled-chromium/repo/fedora-%OS_VERSION%/wojnilowicz-ungoogled-chromium-fedora-%OS_VERSION%.repo
    install:
      - aria2  
      - android-tools  
      - code  
      - dconf-editor  
      - epiphany  
      - fastfetch
      - ffmpegthumbnailer
      - gcc
      - gh  
      - git-credential-oauth  
      - gnome-backgrounds-extras  
      - gnome-tweaks  
      - ibm-plex-mono-fonts  
      - ifuse  
      - iotop  
      - libimobiledevice  
      - liberation-fonts-all  
      - libsss_autofs  
      - libxcrypt-compat  
      - net-tools  
      - NetworkManager-sstp  
      - NetworkManager-sstp-gnome  
      - p7zip  
      - p7zip-plugins  
      - podman-compose
      - podman-docker
      - podmansh
      - sstp-client  
      - subversion  
      - sysprof  
      - tailscale  
      - unrar
      - wireguard-tools  
      - zsh
      - libxcrypt-compat
    remove:
      - gnome-tour
      - gnome-software-rpm-ostree
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-background-logo

  - type: script
    scripts:
      - codec.sh
      - driver.sh
      - patch.sh

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: systemd
    system:
      enabled:
        - flatpak-add-flathub-repo.service
        - flatpak-replace-fedora-apps.service
        - flatpak-cleanup.timer
        - flatpak-cleanup.service
        - rpm-ostreed-automatic.timer
      disabled:
        - flatpak-system-update.timer

  - type: signing