---
name: BlueStream
description: Seamless Daily Computing with Fedora Silverblue at Its Core.

base-image: quay.io/fedora/fedora-silverblue
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: bling
    install:
        - rpmfusion
        - dconf-update-service

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://copr.fedorainfracloud.org/coprs/wojnilowicz/ungoogled-chromium/repo/fedora-%OS_VERSION%/wojnilowicz-ungoogled-chromium-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sunwire/envycontrol/repo/fedora-%OS_VERSION%/sunwire-envycontrol-fedora-%OS_VERSION%.repo
    install:
      - aria2  
      - android-tools
      - code  
      - dconf-editor
      - distrobox
      - fastfetch
      - ffmpegthumbnailer
      - flatpak-spawn
      - fish
      - fzf
      - gcc
      - gh  
      - git-credential-oauth  
      - gnome-backgrounds-extras
      - gnome-epub-thumbnailer
      - gnome-themes-extra
      - gnome-tweaks
      - gvfs-nfs
      - heif-pixbuf-loader
      - ibm-plex-mono-fonts  
      - ifuse  
      - iotop  
      - libimobiledevice  
      - liberation-fonts-all  
      - libsss_autofs  
      - libxcrypt-compat
      - lshw
      - net-tools  
      - NetworkManager-sstp  
      - NetworkManager-sstp-gnome
      - p7zip  
      - p7zip-plugins
      - pipx
      - podman-compose
      - podmansh
      - powerline-fonts
      - python3-envycontrol
      - sstp-client  
      - subversion
      - tailscale
      - tcpdump
      - ungoogled-chromium
      - unrar
      - wireguard-tools
      - yt-dlp
      - zstd
    remove:
      - gnome-tour
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-background-logo
      - gnome-software-rpm-ostree

  - type: script
    scripts:
      - codec.sh
      - driver.sh
      - patch.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter

  - type: systemd
    system:
      enabled:
        - flatpak-add-flathub-repo.service
        - flatpak-replace-fedora-apps.service
        - flatpak-cleanup.timer
        - flatpak-cleanup.service
        - rpm-ostreed-automatic.timer

  - type: signing